### ISSUE TITLE
[Feature] setMetaData

### ISSUE THREAD

**Issue by dimsav** [bugsnag/bugsnag-php#121]
Hello,

As we can see in the [error class](https://github.com/bugsnag/bugsnag-php/blob/9bae5c7f8940a390f8c3ef1b7b83f23419a2cd0c/src/Bugsnag/Error.php#L146) when we use `setMetaData()` the existing meta data gets merged with the one passed as an argument.

Is it possible to implement this feature for the client class [here](https://github.com/bugsnag/bugsnag-php/blob/9bae5c7f8940a390f8c3ef1b7b83f23419a2cd0c/src/Bugsnag/Client.php#L273)?

The reason that is useful is because sometimes we want to pass different  meta data in different places of the app. For example a `user_id` at the authentication service and some other value at some other place of the code. Calling `setMetaData()` twice will keep only the latest information.

Thanks for this nice package!

**Comment by nickma42** [comment]
@dimsav you can use `setUser()` which will actually make a `User` tab in the interface and works separately to the `setMetaData()` so there's no overwriting.

BUT

@bugsnag-github it'd be great to have an `addMetaData` because we have metadata we need to report on from lots of different stages of our app.

**Comment by GrahamCampbell** [comment]
We've got this implemented now. :)
