### ISSUE TITLE
bugsnag lib slow down performance

### ISSUE THREAD

**Issue by muriloazevedo** [bugsnag/bugsnag-php#387]
I tried to install  the php library, but the performance slow down, resulting a high cpu.

I searched a different solution with bugsnag-agent, but I couldn't figured out how to connect at localhost. 

Is there any solution to send this requests async?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, Are you using this in the context of a web server, or some kind of CLI app? Bugsnag already defaults to only sending the reports on request shutdown, after the user has already received the request, and batches sending, to minimize performance impact. Do you know what exactly it is that is causing the high CPU usage?

**Comment by muriloazevedo** [comment]
@GrahamCampbell I made a test and some profiling. It's a legacy application triggering many notices, that's why was consuming too much cpu.

I will try to connect at localhost in other moment.

**Comment by GrahamCampbell** [comment]
Ah, ok. I'm not sure what we can do in the case that your application is erroring thousands of times, in term of performance. Are you using the latest notifier? If so, the time will not be spent waiting on the network for each error, since we batch them.

If there are errors that you don't care about reporting to Bugsnag, you could setup a callback that returns false for the ones you don't want reporting. https://docs.bugsnag.com/platforms/php/other/customizing-error-reports/#adding-callbacks
