### ISSUE TITLE
setFilters doesn't filter out everything

### ISSUE THREAD

**Issue by tsteuwer-accesso** [bugsnag/bugsnag-php#491]
Good evening. We're trying to use the filters option in Bugsnag. It is not behaving as expected. As an example, say I was calling:

```
$client->setFilters(['customer', 'guid', 'country', 'user']);
```
This would actually filter out the `params` section of the `request` tab. The result would be something like this:

*Request Tab*
```
headers: { .... truncated ...}
method: 'GET'
params: {
  "link": "https://asdf.com",
  "_m": "cf-kbf",
  "customer": "[FILTERED]",
  "guid": "[FILTERED]",
  "country": "[FILTERED]",
  "user": "[FILTERED]"
}
url: http://localhost:7000/emails/engine/goodbye/?link=https://asdf.com&_m=cf-kbf&customer=1234234&guid=t32r34o1y&country=us&user=23441273
userAgent
```
But, notice something incorrect? It filters out the `param` values, however, it doesn't filter them out from the `url` in this same tab. Can this please be addressed?

Also, following the documentation, we should be able to completely remove the `request` tab via:

```
$client->registerCallback(function($report) {
   $report->setMetaData([
      'request' => null,
      'details' => [
           .. our own request tab..
      ]
    ]);
});
```

However, this does *not* remove the request tab and everything is still getting reported in there.

Finally, when using the `setFilter` option, it is fuzzy matching ANYTHING with that specific word in it. So even doing:

```
$client->setFilters(['user']);
```

This would filter our the `user` in `param` but it also filters out the `userAgent` in the request tab, which is *not* expected. We still need to see the `userAgent`.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch.

> But, notice something incorrect? It filters out the param values, however, it doesn't filter them out from the url in this same tab. Can this please be addressed?

I think it's by perhaps design that this is not filtered. That said, all is not lost. Bugsnag's PHP notifier does have a powerful middleware/callback system that allows you to intercept and modify report content before it is submitted to Bugsnag. All the documentation is available at https://docs.bugsnag.com/platforms/php/other/customizing-error-reports/. You can implement your own filter that filters the data in exactly the way you need, and then register it with a single function call. You should be able to look for your filter keywords in the URL and adjust the URL as your see fit.

> However, this does not remove the request tab and everything is still getting reported in there.

You'll need to pass `false` as the second parameter to the `setMetaData` function to avoid the new data being merged with the old data (https://github.com/bugsnag/bugsnag-php/blob/v3.14.1/src/Report.php#L495-L508).

> Finally, when using the setFilter option, it is fuzzy matching ANYTHING with that specific word in it.

I think this is by design too. @kattrali will be able to confirm how the other Bugsnag notifiers behave. The current PHP implementation is to check if any of the filtered words appear within the keys of any entries: https://github.com/bugsnag/bugsnag-php/blob/v3.14.1/src/Report.php#L726. It looks like this behaviour has remained the same since it was first implemented in v2.0.0 of Bugsnag PHP (https://github.com/bugsnag/bugsnag-php/commit/3bf08a9d38aa9c95396c6e5917d3735f25de8585#diff-080dfe5d6a1d45923ecf33c6f0e79308R132).

**Comment by tsteuwer-accesso** [comment]
Hey Graham,

Thanks for the response. I'll check those out. So how can you keep 'userAgent' but not 'user'? You guys may want to update your documentation to say that it's a fuzzy match as well 👍.

I set null for 'request' but it still implemented everything. That's my confusion. Your documentation says if you want to remove the 'request' metadata, that's all you have to do. But that's doesn't work. Any other ways to make that happen? I'm assuming that's happening because the request matadata happens last? I did:

```
function ($report) {
   $report->setMetaData([
      'request' => null
   ]);
}
```

But the request tab still comes up in bugsnag with everything.

**Comment by GrahamCampbell** [comment]
You'll need:

```php
function ($report) {
   $report->setMetaData([
      'request' => null
   ], false);
}
```

**Comment by GrahamCampbell** [comment]
You'll need:

```php
function ($report) {
    $data = $report->getMetaData();
    unset($data['request']);
    $report->setMetaData($data, false);
}
```

**Comment by GrahamCampbell** [comment]
Alternatively, you could force the middleware that sets the request in the first place to not register. That is, when you create a new client, set `$defaults = false`: https://github.com/bugsnag/bugsnag-php/blob/v3.14.1/src/Client.php#L77-L100, and then only register the middleware you actually want: https://github.com/bugsnag/bugsnag-php/blob/v3.14.1/src/Client.php#L186-L201 (that's what get called if you allow the defaults to be registered).

**Comment by tsteuwer-accesso** [comment]
That's @GrahamCampbell. That should do the trick. I'll test it out in a bit. We can close this.
