### ISSUE TITLE
Unable to install on PHP 5.5

### ISSUE THREAD

**Issue by sameerpanjwani** [bugsnag/bugsnag-php#543]
Am getting the following error in conposer which comes from the guzzle dependency:

ralouphie/getallheaders 3.0.3 requires php >=5.6 

I can't upgrade to php 5.6 and so is there a workaround?

**Comment by GrahamCampbell** [comment]
This library doesn't depend on ralouphie/getallheaders 3.0.3, and can be installed on PHP 5.5.

**Comment by GrahamCampbell** [comment]
Here's an example of the library being installed on PHP 5.5.9 with Guzzle 5 or 6:

* https://travis-ci.com/bugsnag/bugsnag-php/jobs/228966636
* https://travis-ci.com/bugsnag/bugsnag-php/jobs/228966637

**Comment by GrahamCampbell** [comment]
Looking at Guzzle's dependencies by hand, they allow 2.x too, which is why there will be no issues: https://github.com/guzzle/psr7/blob/master/composer.json#L22.

**Comment by sameerpanjwani** [comment]
Ok my bad. My local environment was 5.6 and so it installed a later version of getallheaders, which wouldn't work on the server which had 5.5. So I just did a `"composer require ralouphie/getallheaders "^2"` to force the v2 to be used.

**Comment by GrahamCampbell** [comment]
Ah, right. You can actually force composer to simulate being any PHP version you like, so that even if you had PHP 7.3 installed locally, you could make sure it resolved dependencies compatible with, say 5.5.9. Set `config.platform.php` to `"5.5.9"` in your `composer.json`. For example, in one of my apps, I have it locked to 64-bit 7.3.5:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/2829600/64950863-4f509d80-d874-11e9-8ebb-026663cef772.png">
