### ISSUE TITLE
Downstream Vulnerability - Guzzle <1.8.4 >=2.0.0, <2.1.1

### ISSUE THREAD

**Issue by jamessampford** [bugsnag/bugsnag-php#645]
### Describe the bug
It seems that Guzzle has security vulnerabilities for <1.8.4 >=2.0.0, <2.1.1 [[https://security.snyk.io/vuln/SNYK-PHP-GUZZLEHTTPPSR7-2431148](https://security.snyk.io/vuln/SNYK-PHP-GUZZLEHTTPPSR7-2431148)]

### Resolution
This can be circumvented by upping the version is 1.8.4/5 or 2.1.1+

**Comment by GrahamCampbell** [comment]
No changes are required in this repo. Composer will already get you the latest if you ask it. If a change were to be made here and you were refusing to upgrade the psr7 dependency, all that would happen is composer would keep using the older version of this library in order to satisfy that constraint.

**Comment by GrahamCampbell** [comment]
> 1.8.4/5 or 2.1.1+

The vulnerability was fixed in 1.8.4, 2.1.1 and 2.2.0, however those versions contained a bug introduced by the fix, which prompted the release of 1.8.5, 2.1.2 and 2.2.1.
