### ISSUE TITLE
Redact command-line options

### ISSUE THREAD

**Issue by danepowell** [bugsnag/bugsnag-php#659]
### Description

I maintain a Symfony Console application. Some commands accept sensitive options such as `--password=12345`. We need to be able to filter these options out of BugSnag reports. I've seen the redactedKeys option but this mainly seems oriented to web requests, and I'm pretty sure it can't work on the console. Anyway, it can't filter out just one option value from the console command.

**Describe the solution you'd like**

A way to filter / redact console options.

**Describe alternatives you've considered**

Removing any sensitive console options from our application entirely, and scolding users for passing sensitive info via the command line. Sure, in an ideal world that would be true, but there's cases where it makes sense.

**Additional context**

**Comment by danepowell** [comment]
Thanks, I sent a screenshot to help clarify.

I saw the [documentation on customizing the error report](https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/) but I didn't see how it helps here. The problem is that the sensitive parameters are in the "location" field (at least I think that's what you'd call it for a web app). They are not in the stack trace or metadata. And I can't see how to modify the reported location.

**Comment by matth-bugsnag** [comment]
Hi Dane, 

Thanks for sending that screenshot to us. From the screenshot I can see that your `--password` values are being included in the context of your events. As mentioned in my last message, it should be possible to remove this using a callback, however, instead of modifying the stack trace, you can modify the events context. To do this, you will need to use the [GetContext](https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/#getcontext) and [SetContext](https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/#setcontext) methods. For instance:
```
public function boot()
{
    parent::boot();
    $this->container->get('bugsnag')->registerCallback(function ($report) {
        $context = $report->getContext();
        if (strpos($context, "--password") !== false) {
            $report->setContext(substr($context, 0, strpos($context, "--password")));
        }
    });
}
```
It’s worth noting that in Symfony, callbacks should be registered within the boot function of your `src/Kernel.php` file, as shown in our docs [here](https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/#setcontext:~:text=In%20Symfony%20callbacks,file).

Please let me know if you have any problems implementing this in your project.

**Comment by danepowell** [comment]
Awesome, thanks! That snippet worked on the first try; very impressive! :) Here's my implementation for anyone who's curious: https://github.com/acquia/cli/pull/1465

I guess I missed in the docs that [Context held this information](https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/#setcontext). In hindsight I should have caught this:
> This is typically set to a filename or request path automatically, depending on the framework and application type.

You mentioned callbacks should be registered on boot. I assume that's to ensure that the callbacks run even on early errors during boot? Our app is a little weird since we don't use the Framework Bundle for performance reasons, and this makes it difficult to access the container in the way you might expect. But we'll take this into consideration.
