### ISSUE TITLE
Get Error ID in Notifier Response

### ISSUE THREAD

**Issue by Antnee** [bugsnag/bugsnag-php#87]
Hi guys,

I was wondering if there's a way to get a unique ID back from the notifier? Presumably the notification is placed in a queue, rather than immediately recorded somewhere, so I appreciate that this may not be immediately possible. It would be useful for us though to generate an error ID and return in an API response for tracking.

Thanks

**Comment by ConradIrwin** [comment]
Hi Antee,

We do indeed just queue incoming requests, so we can't return a unique identifier from the server, and that's unlikely to change.

What some people do is generate a UUID in beforeBugsnagNotify and send it with the crash, so that you can correlate crash reports with logs.

Will that work for you?

Conrad

**Comment by Antnee** [comment]
Yeah, we can do that. Just need to add it across multiple apps. No probs. Thanks for the response
